version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Australia/Sydney
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      routine-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Australia/Sydney
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      routine-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
