import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

interface SkillSource {
  name: string;
  path: string;
}

const repoRoot = join(import.meta.dir, "..");
const outputPath = join(repoRoot, "src", "skills", "embedded.ts");

const skills: SkillSource[] = [
  { name: "wux", path: ".claude/skills/wux/SKILL.md" },
  { name: "dual-review", path: ".claude/skills/dual-review/SKILL.md" },
  { name: "wux-command", path: ".claude/skills/wux-command/SKILL.md" },
  { name: "wux-hub", path: ".claude/skills/wux-hub/SKILL.md" },
];

async function main(): Promise<void> {
  const entries = await Promise.all(
    skills.map(async (skill) => ({
      name: skill.name,
      sourcePath: skill.path,
      content: await readFile(join(repoRoot, skill.path), "utf8"),
    })),
  );
  const rendered = renderEmbeddedModule(entries);
  let existing: string | undefined;
  try {
    existing = await readFile(outputPath, "utf8");
  } catch {
    existing = undefined;
  }
  if (existing === rendered) return;
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, rendered, "utf8");
}

function renderEmbeddedModule(entries: { name: string; sourcePath: string; content: string }[]): string {
  const rows = entries
    .map(
      (entry) =>
        `  { name: ${JSON.stringify(entry.name)}, sourcePath: ${JSON.stringify(entry.sourcePath)}, content: ${JSON.stringify(entry.content)} },`,
    )
    .join("\n");
  return `// Generated by scripts/generate-skills.ts. Do not edit by hand.

export interface EmbeddedSkill {
  name: string;
  sourcePath: string;
  content: string;
}

export const BUNDLED_SKILLS: readonly EmbeddedSkill[] = [
${rows}
];
`;
}

await main();
